### ISSUE TITLE
node genAddress.js err

### ISSUE THREAD

**Issue by watchpoints** [rebase-network/ckb-wallet-generator#2]
>  Distributor ID: Ubuntu
> Description:    Ubuntu 18.04.2 LTS
> Release:        18.04
> Codename:       bionic
> x86_64 x86_64 GNU/Linux

### node genAddress.js 

`(node:15923) UnhandledPromiseRejectionWarning: Error: connect E**CONNREFUSED 127.0.0.1:8114**
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)

(node:15923) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:15923) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
root@work:~/wangchuanyi/money/ckb-wallet-generator# node sendTransaction.js
/root/wangchuanyi/money/ckb-wallet-generator/sendTransaction.js:158
      capacity: 0n,
                ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3`

**Comment by luckyyang** [comment]
你需要跑一个本地的ckb节点

**Comment by luckyyang** [comment]
`ckb run`

**Comment by liushooter** [comment]
or you can choice [new](https://github.com/rebase-network/ckb-wallet-generator/blob/new/newGenAddress.js) brance

**Comment by luckyyang** [comment]
我已经merge了new branch， @aleafboat pull一下代码重新运行应该ok了
